### ISSUE TITLE
[BUG] pytkdocs must be installed with 'numpy-style'

### ISSUE THREAD

**Issue by rodrigomologni** [mkdocstrings/pytkdocs#104]
**Describe the bug**

`mkdocs build` is producing the following message: `pytkdocs must be installed with 'numpy-style' extra to parse Numpy docstrings`. I verified that this warning is not being displayed because of the absence of `numpy-style`, but because of the absence of `docstring_parser`. I suggest to include this package in the `mkdocstrings` or `pytkdocs` requirements. `mkdocs build` produced documentation with NumPy style after the installation of the `docstring_parser` package.

**System (please complete the following information):**
- `pytkdocs` version 0.11.1
- Python version: 3.8.9
- OS: Windows 10 x64

**Comment by pawamoy** [comment]
As stated by the error message, you must install pytkdocs with the `numpy-style` extra, which means for example that you must use `pip install 'pytkdocs[numpy-style]'`. If you have it listed in a requirements.txt file, it's the same syntax.

**Comment by rodrigomologni** [comment]
> pip install 'pytkdocs[numpy-style]'

Perfect! It's is running! Thank you!

> As stated by the error message, you must install pytkdocs with the numpy-style extra...

I suggest to include `pip install pytkdocs[numpy-style]` in the warning message. I didn't find instructions on how to install `pytkdocs` like `numpy-style` extra.

**Comment by pawamoy** [comment]
Yes, good idea, I'll do that, thanks :)

**Comment by rodrigomologni** [comment]
I thank you for your help! ;-)
