### ISSUE TITLE
[BUG] collections.namedtuple leads to source not found warning

### ISSUE THREAD

**Issue by ArneBachmannDLR** [mkdocstrings/pytkdocs#111]
**Describe the bug**
I declare a few named tuples in my code, which leads to:
```
←[33mWARNING  -  ←[0mmkdocstrings.handlers.python: Couldn't read source for 'autocook.python.PackageVersion.__new__': could not get source code
←[33mWARNING  -  ←[0mmkdocstrings.handlers.python: Couldn't read source for 'autocook.windows.WindowsService.VALUE.__new__': could not get source code
```

**To Reproduce**
Here is the code:
```
class WindowsService(WindowsServiceRemoval):
  ''' long docstring '''
  VALUE:NamedTuple = collections.namedtuple("VALUE", "required nssmKey quotes type")

  def __init__(_, name:str) -> None:
    pass
```

**Expected behavior**
Nothing special, just no warning.

**System (please complete the following information):**
- `pytkdocs` version 0.11.1
- Python version: 3.8.8
- OS: Windows 20H2 with Miniforge Python

**Comment by pawamoy** [comment]
I agree that these warnings are annoying or even disrupting with the strict mode enabled. We can probably add a special cases, or some configuration option to choose what warnings to disable.
