### ISSUE TITLE
[BUG] Wrong version from python package

### ISSUE THREAD

**Issue by Yajo** [mkdocstrings/pytkdocs#122]
**Describe the bug**
It seems mkdocs is not rendering the appropriate package version.

**To Reproduce**
Generate docs for Copier at https://github.com/copier-org/copier/commit/3fd822664914914de0ea3b7fd67288d888ea3121.

**Expected behavior**
The displayed version should be `6.0.0a9.post2.dev0+3fd8226` (which is the one you get from `copier --version` if you install it with pipx from git).

**Screenshots**
See it live in https://copier.readthedocs.io/en/latest/ (today... it changes over time of course):

![imagen](https://user-images.githubusercontent.com/973709/140701081-ac3193ca-9634-46c7-babb-66b190d832c5.png)

**System (please complete the following information):**
- `pytkdocs` version 0.12.0
- Python version: 3.8
- OS: Linux

**Additional context**
I use https://github.com/mtkennerly/poetry-dynamic-versioning to autogenerate the version from the commit.

**Comment by pawamoy** [comment]
Oh, you probably need to open this on the mkdocs-material repository, as I think it's the one retrieving and displaying the tag.

**Comment by pawamoy** [comment]
Yes in fact I think it's simply querying GitHub to get the latest tag. Your local version won't show up, unless you use a plugin maybe.
