### ISSUE TITLE
[BUG] Support typing-extensions 4.x

### ISSUE THREAD

**Issue by lyz-code** [mkdocstrings/pytkdocs#124]
**Describe the bug**
`typing-extensions` version `4.` is out, it would be nice to update the version pin if possible.

**To Reproduce**
Install the latest version of `pytkdocs`

**Expected behavior**
The latest version of `typing-extension` is installed.

**System (please complete the following information):**
- `pytkdocs` version `0.12.0`
- Python version: `3.9`
- OS: Linux

**Comment by pawamoy** [comment]
Sure, also based on this article https://iscinumpy.dev/post/bound-version-constraints/, I think I'll just remove the upper bound.

**Comment by lyz-code** [comment]
Lovely article, thank you so much. I'm going to remove the upper bounds of my libraries too
