### ISSUE TITLE
[DOCS] Docstrings don't match up with function parameters

### ISSUE THREAD

**Issue by thatlittleboy** [mkdocstrings/pytkdocs#135]
While I was working on #134 , I realized many of the functions in `pytkdocs.parsers.docstrings.numpy` have wrongly annotated docstrings (params don't match up with what's written in docstring).

For example: https://github.com/mkdocstrings/pytkdocs/blob/master/src/pytkdocs/parsers/docstrings/numpy.py#L49

I think this could be a easy & quick fix --- shall I address this in a subsequent PR ?  🙂

**Comment by pawamoy** [comment]
Oh, indeed, thanks for catching that. The Numpy parser was added by @aschmu, and I admit I probably was not thorough when reviewing it, because I never use Numpydoc :smile: Of course, feel free to send a new PR, this is highly appreciated!
