### ISSUE TITLE
Add support for django models

### ISSUE THREAD

**Issue by mRokita** [mkdocstrings/pytkdocs#39]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to document Django models without adding docstrings, just like pydantic models.

**Describe the solution you'd like**
Add similar support for Django models

**Describe alternatives you've considered**
Adding docstrings to every model field, I don't really like it because usually it means duplicating verbose_name value.

**Comment by pawamoy** [comment]
(basic?) Support added for Django models in #101
