### ISSUE TITLE
Support default values for pydantic fields

### ISSUE THREAD

**Issue by chbndrhnns** [mkdocstrings/pytkdocs#50]
**Is your feature request related to a problem? Please describe.**
Pydantic models can be documented via the new Attributes category. However, the default values are missing from the table.

**Describe the solution you'd like**
For this example,

```python
from pydantic import BaseModel

class M(BaseModel):
   number: int = 2
```

pytkdocs should add `2` as the default for the field `number`.

**Comment by pawamoy** [comment]
When I added support for `Attributes` section, I forgot about Pydantic attributes, and told myself "attributes don't have defaults" :sweat_smile:

**Comment by camold** [comment]
Great to hear this feature is planned for version 0.11. Would be very useful to avoid redundancy in the docstrings (we currently have to state the default values in the docstring).
Just as a note, pydantic also allows for constraints, e.g. `Field(1, ge=0, le=2)` for the definition of an attribute with values between 0 and 2. These constraints do not seem to show up in `__fields__` or `__field_defaults__` though. So I guess there is no hope of having them included in the docs as well?

**Comment by pawamoy** [comment]
Yes, there is, but it requires a complete refactor of pytkdocs, which I'm working on. Finding the right architecture and data structures will take some time :slightly_smiling_face:

**Comment by theoqian** [comment]
Same issue with attributes in class based on dataclass.

**Comment by pawamoy** [comment]
This won't be implemented here (unless someone sends a PR), but rather in [Griffe](https://github.com/mkdocstrings/griffe), as an extension. Feel free to open a feature request there (it's already in my backlog though, so I'll get to it eventually).
