### ISSUE TITLE
Dataclasses attributes get picked up twice

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/pytkdocs#52]
**Describe the bug**
Dataclasses attributes are picked up twice, because they appear in the direct members, and then we iterate on `__dataclass_fields__` again.

**To Reproduce**
```python
@dataclass
class FrozenPerson:
    """I'm a frozen person."""

    say: str = "Oh no"
    """Say attr."""
```

**Expected behavior**
Attributes are picked up only once.

**Screenshots**
![Screenshot_2020-06-19_18-42-34](https://user-images.githubusercontent.com/3999221/85158132-aa2c8080-b25c-11ea-962a-130e1a1d7e12.png)

**System (please complete the following information):**
- `pytkdocs` 0.6.0
- Python version: 3.7
- OS: Linux

**Comment by beanaroo** [comment]
I've noticed this only affects the last attribute:

```python
@dataclass
class C:
    """A C dataclass """

    a: int
    """a: A required number"""

    b: int = 0
    """ b: An optional number with default to 0"""
```

![image](https://user-images.githubusercontent.com/1748909/96320002-a0c9ee00-106d-11eb-9023-a684914448bf.png)

**Comment by Yajo** [comment]
I'm having it for various attrs here: https://copier--314.org.readthedocs.build/en/314/reference/template/

**Comment by bstadlbauer** [comment]
Seems like only attributes with default values are duplicated

**Comment by bstadlbauer** [comment]
I've added a possible fix for this in PR https://github.com/mkdocstrings/pytkdocs/pull/100
