### ISSUE TITLE
Enable the inheritance of classmethod for docstrings

### ISSUE THREAD

**Issue by cgarciae** [mkdocstrings/pytkdocs#58]
Currently the docstrings for inherited classmethods are completely ignored, this forces the user make trivial reimplementation of methods such as `__init__` just to show proper documentation.

Original disscutions: https://github.com/pawamoy/mkdocstrings/issues/78#issuecomment-664537828

**Comment by astair** [comment]
Are there any news about this? Being able to inherit __init__ docstrings would be super helpful! It also seems like even docstrings of reimplemented __init__ methods are not displayed for subclassed methods.

**Comment by samsja** [comment]
Is there any news on this ?

**Comment by pawamoy** [comment]
Hello, no news unfortunately! Pull requests are welcome if you want to try and fix this. Based on this previous comment of mine, it should be fairly easy:

> Oh, yeah, it happens here: https://github.com/pawamoy/pytkdocs/blob/master/src/pytkdocs/loader.py#L587-L600. I think we could safely remove this since we can now chose to inherit or not.

**Comment by samsja** [comment]
@pawamoy Thanks. I will try to take a look and maybe do a PR if a find a fix

**Comment by pawamoy** [comment]
If you still experience this issue, please comment, and I'll reopen. If you comment, please do provide a minimal reproduction example (some code that demonstrate the issue), thanks!
