### ISSUE TITLE
Add Enum values

### ISSUE THREAD

**Issue by StephenBrown2** [mkdocstrings/pytkdocs#61]
**Is your feature request related to a problem? Please describe.**

When documenting Enums, I will usually want to show the value of the enum, rather than just it's reference, to show the valid options.

**Describe the solution you'd like**

Rather than duplicating the enum in the docstring, I would prefer if a subclass of `enum.Enum` is encountered, the value of each attribute is shown next to it. Bonus: the value is color-highlighted with python syntax.

**Describe alternatives you've considered**

1. Documenting the Enum completely in markdown:

> ### ServiceCancelReasons
> 
> An Enum defining the valid Cancellation reasons for a Service
> 
> ```python
> CUSTOMER_REQUEST = "Customer Request"
> INCORRECT_DATE_OR_TIME = "Incorrect Date Or Time"
> OTHER = "Other"
> ```

2. Documenting each attribute with duplicating the value:

> ```python
> class MaintenanceStateIds(IntEnum):
>     """Valid IDs for Maintenance states."""
> 
>     TEMPORARY = 1
>     """Temporary: 1"""
>     TENTATIVE = 2
>     """Tentative: 2"""
>     SCHEDULED = 3
>     """Scheduled: 3"""
>     CANCELLED = 4
>     """Canceled: 4"""
>     COMPLETED = 5
>     """Completed: 5"""
> ```

3. Documenting using a combination of the above, duplicating the values in the top-level docstring.

> ```python
> class ServiceCancelReasons(str, Enum):
>     """Valid reasons to cancel a service.
> 
>     ```python
>     CUSTOMER_REQUEST = "Customer Request"
>     INCORRECT_DATE_OR_TIME = "Incorrect Date Or Time"
>     OTHER = "Other"
>     ```
>     """
> 
>     CUSTOMER_REQUEST = "Customer Request"
>     INCORRECT_DATE_OR_TIME = "Incorrect Date Or Time"
>     OTHER = "Other"
> ```

**Additional context**

Ideally, I could do something like the following:
```python
class MaintenanceStateIds(IntEnum):
    """Valid IDs for Maintenance states."""

    TEMPORARY = 1
    """Maintenance is in a temporary state, before scheduling or confirming any time slots"""
    TENTATIVE = 2
    """Maintenance slot is being tentatively held on the calendar"""
    SCHEDULED = 3
    """Maintenance has been confirmed for a particular time slot on the calendar to be executed"""
    CANCELLED = 4
    """Maintenance was cancelled before execution"""
    COMPLETED = 5
    """Maintenance was completed, status is dependent on states of services"""

class MaintenanceStateNames(str, Enum):
    """Valid names for Maintenance states."""

    TEMPORARY = "Temporary"
    """Maintenance is in a temporary state, before scheduling or confirming any time slots"""
    TENTATIVE = "Tentative"
    """Maintenance slot is being tentatively held on the calendar"""
    SCHEDULED = "Scheduled"
    """Maintenance has been confirmed for a particular time slot on the calendar to be executed"""
    CANCELLED = "Canceled"
    """Maintenance was cancelled before execution"""
    COMPLETED = "Completed"
    """Maintenance was completed, status is dependent on states of services"""
```

and end up with the results (achieved through some quick HTML hacking):
<img width="682" alt="Screenshot 2020-07-30 at 10 50 39" src="https://user-images.githubusercontent.com/1148665/88951383-2306fb00-d253-11ea-9b30-df44ef286702.png">
<img width="695" alt="Screenshot 2020-07-30 at 10 53 17" src="https://user-images.githubusercontent.com/1148665/88951385-24382800-d253-11ea-876c-e759bdf22052.png">

**Comment by pawamoy** [comment]
Agreed :slightly_smiling_face: 

I think we can generally improve this. Documented attributes could always show the value (or *default* value in case of, for example, Pydantic fields, see #50).

There's an alternative you did not consider here, now that pytkdocs reads Attributes sections, though it would still need new code to get the values:

```python
class MaintenanceStateIds(IntEnum):
    """
    Valid IDs for Maintenance states.

    Attributes:
        TEMPORARY: Maintenance is in a temporary state, before scheduling or confirming any time slots.
        TENTATIVE: Maintenance slot is being tentatively held on the calendar.
        SCHEDULED: Maintenance has been confirmed for a particular time slot on the calendar to be executed.
        CANCELLED: Maintenance was cancelled before execution.
        COMPLETED: Maintenance was completed, status is dependent on states of services.
    """
    ...  # actual attributes

class MaintenanceStateNames(str, Enum):
    """
    Valid names for Maintenance states.

    Attributes:
        TEMPORARY: Maintenance is in a temporary state, before scheduling or confirming any time slots.
        TENTATIVE: Maintenance slot is being tentatively held on the calendar.
        SCHEDULED: Maintenance has been confirmed for a particular time slot on the calendar to be executed.
        CANCELLED: Maintenance was cancelled before execution.
        COMPLETED: Maintenance was completed, status is dependent on states of services.
    """
    ...  # actual attributes
```

Note however that using an Attributes section results in the attributes being shown in a table, instead of as a list of objects with headings. Therefore you cannot cross-reference a particular enum value when using an Attributes table.

Anyway, in both cases (Attributes section and table rendering, triple-quoted docstrings for each value and list rendering plus permalinks), we could improve the rendering and show the [default] values.

**Comment by StephenBrown2** [comment]
For the HTML I just stole from the highlighted classes for python code, I believe they were spans with `.o` for the operator (equals sign), `.s2` for strings and `.mi` for integers, in the same `<code class="highlight">` tag as the attribute.

**Comment by pawamoy** [comment]
The [new handler](https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers) is able to pick up attributes values and to display them in the rendered HTML :slightly_smiling_face: Feedback appreciated!

**Comment by pepijnvtol** [comment]
@pawamoy Which handler should I use? Do you have a link to the documentation?

**Comment by pawamoy** [comment]
Yes, see https://mkdocstrings.github.io/python.

**Comment by pepijnvtol** [comment]
Do you mean this? https://mkdocstrings.github.io/python/usage/configuration/docstrings/#with-attributes

When I add this code:
```
from enum import Enum, auto
from pydantic import BaseModel


class Test:
    def __init__(self, x: float, y: float) -> None:
        """Create a Test class

        This test class is used to test the documentation

        """
        self.x = x
        self.y = y


class Testv1(BaseModel):
    """Test v2 class"""

    x: float
    y: float


class Testv2(Enum):
    """test enum"""

    a = "Value A"
    b = "Value B"

```

None of the attributes are in the documentation, only if I include them in the docstring manually. I am using verion 1.6.1 (>0.18). 

I think that this is also relevant:

```
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table
            # merge_init_into_class: true
            show_if_no_docstring: false
            inherit-member: true
```

Could you clarify how to automatically include the attributes in the documentation?

**Comment by pawamoy** [comment]
Your attributes don't have docstrings, so you must set `show_if_no_docstring: true` for them to show up.

**Comment by pepijnvtol** [comment]
Okay, the result is not exactly what I expected, but it worked. I really appreciate all the hard work you've put into this project and your time in helping me out!

**Comment by pawamoy** [comment]
Don't hesitate to open new issues if you think something is not working as it should :slightly_smiling_face:
