### ISSUE TITLE
[FeatureRequest] Support the numpy docstring format

### ISSUE THREAD

**Issue by dhirschfeld** [mkdocstrings/pytkdocs#7]
The numpy docstring format is very popular in the scientific python community.

The numpy docstring format is supported by the [`numpydoc`](https://numpydoc.readthedocs.io/en/latest/format.html) and [`napoleon`](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#module-sphinx.ext.napoleon) sphinx extensions.

**Comment by pawamoy** [comment]
Pull requests are welcome. All the code related to the parsing of docstrings is in https://github.com/pawamoy/pytkdocs/blob/master/src/pytkdocs/parsers/docstrings.py. Feel free to try and add support for other docstrings format! If you have any questions, ask on Gitter: https://gitter.im/pytkdocs/community

**Comment by pawamoy** [comment]
There's a base parser now (#28). This should ease (slightly) the process of implementing another parser. Just copy paste the google parser into a new `numpy.py` module, and adapt the code :slightly_smiling_face:! The only method that must be implemented in the parser subclass is `parse_sections`.
