### ISSUE TITLE
[BUG] individually annotated attributes in __init__ not discovered

### ISSUE THREAD

**Issue by drwelby** [mkdocstrings/pytkdocs#93]
**Describe the bug**
The docs seem to indicate that individually annotated attributes in `__init__` should work, but they do not get rendered.

**To Reproduce**

```python
class thing():
    ''' docstring of a thing '''

    def __init__(self):

        #: an A
        self.a = 'A'

        self.b : str = 'B' #: a B
        
        self.c = 'C'
        ''' a C '''
```
and
```
## A thing

::: module.thing
```

**Expected behavior**
I would expect these to show up in the attribute table.

**Screenshots**
<img width="447" alt="Screen Shot 2021-02-16 at 12 06 06 PM" src="https://user-images.githubusercontent.com/152875/108115746-6722e700-704f-11eb-9905-9d687496fe98.png">

**System (please complete the following information):**
```
mkdocs                    1.1.2                    pypi_0    pypi
mkdocs-material           6.1.0                    pypi_0    pypi
mkdocs-material-extensions 1.0.1                    pypi_0    pypi
mkdocstrings              0.14.0                   pypi_0    pypi
pytkdocs                  0.10.1                   pypi_0    pypi
```
- `Python 3.7.6 | packaged by conda-forge | (default, Mar  5 2020, 15:03:29)`
-  OS X 10.14.6

**Comment by pawamoy** [comment]
We do not support type annotations in comments ^^ but `self.c` should definitely be picked up with its docstring and rendered. Will investigate.

**Comment by pawamoy** [comment]
This is likely solved by the [new handler](https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers). Feedback appreciated!
