### ISSUE TITLE
[BUG] Pydantic Field documentation generates wrong type for List/Set/Tuple

### ISSUE THREAD

**Issue by shashankrnr32** [mkdocstrings/pytkdocs#94]
**Describe the bug**
pydantic fields with _outer_type_ (Eg. `typing.List`, `typing.Set` etc) are populated with the wrong type in documentation. The documentation shows only the inner type. (See example)

**To Reproduce**
```python
from typing import List, Union
from pydantic import BaseModel, Field

class MyModel(BaseModel):
    """
    MyModel
    """
    attr_bug: List[str] = Field(..., description="This is a mock attribute that is buggy")
    attr_perfect: Union[List[str], List[int]] = Field(description="This is a mock attribute that is perfect")
```

1. The type information of the `attr_bug` shows up as `str` and not `List[str]` (which is expected)
2. The type information of the `attr_perfect` shows up as `Union[List[str], List[int]]` as expected

**Expected behavior**

Explained above below the code example.

**Screenshots**
Attaching a screenshot of the documentation produced by mkdocstrings with the above example code

<img width="683" alt="Screenshot 2021-02-20 at 9 52 40 AM" src="https://user-images.githubusercontent.com/29425899/108583690-634dd800-7361-11eb-87b8-564258eda919.png">

**System (please complete the following information):**
- `pytkdocs` version : 0.10.1
- `mkdocstrings` version : 0.14.0 
- Python version: 3.6.1 (I know I should update!!)
- OS: macOS

**Additional context**

According to my quick run through the code of `pytkdocs` and `pydantic`, the reason is most probably because of the below line. 

https://github.com/mkdocstrings/pytkdocs/blob/bf04764f1608970643932329c9f6c8c63a0c5632/src/pytkdocs/loader.py#L682

Instead of the above line, it should have been `prop.outer_type_` (that is provided by pydantic [here](https://github.com/samuelcolvin/pydantic/blob/b7a8ef25c667b5dd4c4cd0b109c6625d1a57139a/pydantic/fields.py#L305
)). 

Debug code

```python
print(MyModel.__dict__["__fields__"]["attr_bug"].type_)
# prints <class 'str'>

print(MyModel.__dict__["__fields__"]["attr_bug"].outer_type_)
# prints typing.List[str]
```

--- 
Lastly, thank you very much for creating mkdocstrings (and pytkdocs)

**Comment by pawamoy** [comment]
Hello, thank you very much for the detailed bug report and the PR :slightly_smiling_face: I've left a comment on the PR.
